runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.app
  secure: always

- url: /setconfig
  script: main.app
  secure: always

- url: /getconfig
  script: getconfig.app
  secure: always
